# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea76d5c91d9682d4aade0ae97c4f37a040ae9241deb02d1cb4abcbaf4f05e9a71b447f5f58698cc4a8d3f9ff41d94e44e72b65e48ea721eff6eb12db28f9bab2

test:
  secret_key_base: 5677597dede6cba914f1e40b7bebd382b741de62cbcfb060b30216aae4a6e55c56fb100f72bae7e2057f2dc2d725729dbbecff6d21fd09918370bf787b1cd01d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
